CREATE TABLE booking_elements (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    booking_id BIGINT UNSIGNED NOT NULL,
    element_type VARCHAR(30) NOT NULL,
    title VARCHAR(200) NOT NULL,
    element_booked_date DATE NOT NULL,
    supplier_name VARCHAR(200) NULL,
    supplier_reference VARCHAR(100) NULL,
    service_start_date DATE NULL,
    service_end_date DATE NULL,
    selling_price DECIMAL(13,2) NOT NULL DEFAULT 0.00,
    supplier_cost DECIMAL(13,2) NOT NULL DEFAULT 0.00,
    commission DECIMAL(13,2) NOT NULL DEFAULT 0.00,
    supplier_payment_status VARCHAR(20) NOT NULL DEFAULT 'Not Due',
    supplier_payment_due_date DATE NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Confirmed',
    notes TEXT NULL,
    created_by_user_id BIGINT UNSIGNED NOT NULL,
    updated_by_user_id BIGINT UNSIGNED NOT NULL,
    created_at_utc TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at_utc TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_booking_elements_type (booking_id, element_type),
    KEY idx_booking_elements_status (booking_id, status),
    KEY idx_booking_elements_supplier_reference (supplier_reference),
    KEY idx_booking_elements_payment_due (supplier_payment_status, supplier_payment_due_date),
    KEY idx_booking_elements_service_start (service_start_date),
    KEY idx_booking_elements_created_by (created_by_user_id),
    KEY idx_booking_elements_updated_by (updated_by_user_id),
    CONSTRAINT chk_booking_elements_type CHECK (element_type IN ('Attraction','Travel Insurance','Airport Parking','Airport Hotel','Car Hire','Transfer','Flight','Accommodation','Cruise','Excursion','Lounge','Rail','Upgrade','Other')),
    CONSTRAINT chk_booking_elements_money CHECK (selling_price >= 0 AND supplier_cost >= 0 AND commission >= 0),
    CONSTRAINT chk_booking_elements_dates CHECK (service_start_date IS NULL OR service_end_date IS NULL OR service_end_date >= service_start_date),
    CONSTRAINT chk_booking_elements_payment_status CHECK (supplier_payment_status IN ('Not Due','Due','Paid')),
    CONSTRAINT chk_booking_elements_status CHECK (status IN ('Confirmed','Cancelled','Archived')),
    CONSTRAINT fk_booking_elements_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_booking_elements_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_booking_elements_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

UPDATE installation_metadata SET schema_version='4.0.2-booking-elements';
